## Every music piece and racing theme, GENERATED by the importer from
## `music.lst` + `racing_themes.lst`.
##
## Two of the ten pieces are unreferenced in the original — `freezingpoint` and
## `raceintro` are in `music.lst` and named by nothing — so they are carried
## here rather than dropped: the list is what the data says, and the shell can
## reach for them later.
@tool
class_name MusicLibrary
extends Resource

const PATH := "res://resources/audio/music.tres"

@export var tracks: Array[MusicTrack] = []
@export var themes: Array[MusicTheme] = []

## `param.menu_music` / `credits_music` / `config_music`, whose defaults in
## `game_config.cpp` are the only place these three pieces are named.
@export var menu_track: StringName = &"start_1"
@export var credits_track: StringName = &"credits_1"
@export var options_track: StringName = &"options_1"

var _by_id: Dictionary = {}
var _themes_by_id: Dictionary = {}

static func load_default() -> MusicLibrary:
	if ResourceLoader.exists(PATH):
		var lib: MusicLibrary = load(PATH)
		if lib != null:
			return lib
	return MusicLibrary.new()

## The track's `res://assets/music/...` path, empty if `id` names nothing.
## A path rather than the loaded [AudioStream] — see [member MusicTrack.stream_path].
func track(id: StringName) -> String:
	if _by_id.size() != tracks.size():
		_reindex()
	var t: MusicTrack = _by_id.get(id, null)
	return t.stream_path if t != null else ""

## The named theme, falling back to the first one.
##
## `racing_themes.lst` states that contract in its own header — "The first
## entry is the default theme. In the case there is a mistake or a file doesn't
## exist, the programm falls back to the default" — while `CMusic::PlayTheme`
## actually just fails on an unknown index and leaves whatever was playing.
## Every shipped course names `normal`, `calm` or `spunky`, so the two are
## indistinguishable on the real data; the file's stated contract wins because
## it degrades to music rather than to whichever menu track was last up.
func theme(id: StringName) -> MusicTheme:
	if _themes_by_id.size() != themes.size():
		_reindex()
	var t: MusicTheme = _themes_by_id.get(id, null)
	if t != null:
		return t
	return themes[0] if not themes.is_empty() else null

func _reindex() -> void:
	_by_id.clear()
	for t: MusicTrack in tracks:
		if t != null and not t.id.is_empty():
			_by_id[t.id] = t
	_themes_by_id.clear()
	for th: MusicTheme in themes:
		if th != null and not th.id.is_empty():
			_themes_by_id[th.id] = th
