## Every effect the game can play, GENERATED by the importer from `sounds.lst`.
##
## One resource for the whole game rather than per-course references: the ten
## effects total 4 MB and are shared by all 44 courses, so the alternative
## would pull the same streams into every course pack.
@tool
class_name SoundBank
extends Resource

const PATH := "res://resources/audio/sounds.tres"

@export var cues: Array[SoundCue] = []

var _by_id: Dictionary = {}

static func load_default() -> SoundBank:
	if ResourceLoader.exists(PATH):
		var bank: SoundBank = load(PATH)
		if bank != null:
			return bank
	return SoundBank.new()

## The cue with this id, or null. ETR's `GetSoundIdx` returns `(size_t)-1` for
## an unknown name and every caller then quietly does nothing; null carries the
## same meaning without the wraparound.
func cue(id: StringName) -> SoundCue:
	if _by_id.size() != cues.size():
		_reindex()
	return _by_id.get(id, null)

func has_cue(id: StringName) -> bool:
	return cue(id) != null

func ids() -> Array[StringName]:
	var out: Array[StringName] = []
	for c: SoundCue in cues:
		out.push_back(c.id)
	return out

func _reindex() -> void:
	_by_id.clear()
	for c: SoundCue in cues:
		if c != null and not c.id.is_empty():
			_by_id[c.id] = c
