## Every playable course as a flat list, cheap enough to load at startup.
##
## GENERATED by the importer into [constant PATH]. The menu needs a course
## index that survives an export: `DirAccess` over `res://courses/` finds
## nothing in a shipped build, because the exporter converts and remaps text
## resources out of their source paths. A resource written at import time is
## the only listing that is the same in the editor, in a native build and in
## the browser.
@tool
class_name CourseCatalog
extends Resource

const PATH := "res://resources/courses.tres"

## Groups appear in this order in the menu; anything else sorts after them.
const GROUP_ORDER: Array[String] = ["default", "extras"]

@export var entries: Array[CourseListing] = []

## The generated catalog, or — if it is missing — one scanned from the course
## directories. The fallback only works when running from source, which is
## exactly where a stale checkout would be missing the file.
static func load_default() -> CourseCatalog:
	if ResourceLoader.exists(PATH):
		var cat: CourseCatalog = load(PATH)
		if cat != null and not cat.entries.is_empty():
			return cat
	return scan()

## Degraded index built from directory names alone. No `course.tres` is opened:
## loading 44 of them to fill in an author line would also load 44 heightmaps.
static func scan() -> CourseCatalog:
	var cat := CourseCatalog.new()
	var dir := DirAccess.open("res://courses")
	if dir == null:
		return cat
	for name: String in dir.get_directories():
		var scene: String = "res://courses/%s/course.tscn" % name
		if not ResourceLoader.exists(scene):
			continue
		var listing := CourseListing.new()
		listing.dir = name
		listing.display_name = name.replace("_", " ").capitalize()
		listing.scene_path = scene
		listing.course_path = "res://courses/%s/course.tres" % name
		listing.preview_path = "res://courses/%s/preview.png" % name
		cat.entries.push_back(listing)
	cat.sort()
	return cat

## Group first — the original Tux Racer courses before the community extras —
## then alphabetically by the name the player sees.
func sort() -> void:
	entries.sort_custom(func(a: CourseListing, b: CourseListing) -> bool:
		var ga: int = GROUP_ORDER.find(a.group)
		var gb: int = GROUP_ORDER.find(b.group)
		if ga < 0: ga = GROUP_ORDER.size()
		if gb < 0: gb = GROUP_ORDER.size()
		if ga != gb:
			return ga < gb
		return a.title().naturalnocasecmp_to(b.title()) < 0)
