## Every playable course as a flat list, cheap enough to load at startup.
##
## GENERATED by the importer into [constant PATH]. The menu needs a course
## index that survives an export: `DirAccess` over `res://courses/` finds
## nothing in a shipped build, because the exporter converts and remaps text
## resources out of their source paths. A resource written at import time is
## the only listing that is the same in the editor, in a native build and in
## the browser.
@tool
class_name CourseCatalog
extends Resource

const PATH := "res://resources/courses.tres"

## The courses the original Tux Racer shipped. ETR's own data is what says so:
## these five are the ones by Jasmin Patry, the only ones on `[env] tuxracer`,
## and the whole of `events.lst`'s "Tux Racer Classics" ("courses that shipped
## with the original Tux Racer"). The rest of ETR's `default` group — Chinese
## Wall, Milos Castle and fifteen more — came with ETR, so ETR's group cannot
## stand in for this list.
const TUXRACER_ORIGINALS: Array[String] = ["bunny_hill", "twisty_slope",
	"bumpy_ride", "frozen_river", "path_of_daggers"]

@export var entries: Array[CourseListing] = []

## The generated catalog, or — if it is missing — one scanned from the course
## directories. The fallback only works when running from source, which is
## exactly where a stale checkout would be missing the file.
static func load_default() -> CourseCatalog:
	if ResourceLoader.exists(PATH):
		var cat: CourseCatalog = load(PATH)
		if cat != null and not cat.entries.is_empty():
			return cat
	return scan()

## The shipped catalog plus the courses the player added by address
## ([ExternalCourses]) — what the shell lists and looks courses up in. A fresh
## catalog every call: [method load_default] hands out the cached resource, and
## appending to that would add the external rows again on every call.
##
## The shell's only; the suite asserts over [method load_default], which never
## depends on what somebody once typed into a menu on the machine running it.
static func load_with_external() -> CourseCatalog:
	var cat := CourseCatalog.new()
	cat.entries = load_default().entries.duplicate()
	cat.entries.append_array(ExternalCourses.listings())
	cat.sort()
	return cat

## Degraded index built from directory names alone. No `course.tres` is opened:
## loading 44 of them to fill in an author line would also load 44 heightmaps.
static func scan() -> CourseCatalog:
	var cat := CourseCatalog.new()
	var dir := DirAccess.open("res://courses")
	if dir == null:
		return cat
	for name: String in dir.get_directories():
		var scene: String = "res://courses/%s/course.tscn" % name
		if not ResourceLoader.exists(scene):
			continue
		var listing := CourseListing.new()
		listing.dir = name
		listing.display_name = name.replace("_", " ").capitalize()
		listing.scene_path = scene
		listing.course_path = "res://courses/%s/course.tres" % name
		listing.preview_path = "res://courses/%s/preview.png" % name
		cat.entries.push_back(listing)
	cat.sort()
	return cat

## The row for [param dir], or `null`. A saved run names a course by directory,
## and a course removed from the build since it was saved is exactly that.
func find(dir: String) -> CourseListing:
	for e: CourseListing in entries:
		if e.dir == dir:
			return e
	return null

## Category first — Tux Racer's, then ETR's, then the player's own (see
## [enum CourseListing.Category]), those by the server name they were added
## under — then alphabetically by the name the player sees.
func sort() -> void:
	entries.sort_custom(func(a: CourseListing, b: CourseListing) -> bool:
		if a.category() != b.category():
			return a.category() < b.category()
		var servers: int = a.server_name.naturalnocasecmp_to(b.server_name)
		if servers != 0:
			return servers < 0
		return a.title().naturalnocasecmp_to(b.title()) < 0)
