## The race: wires the node-free simulation to everything that draws.
##
## Layering per godot-port-plan.md §4.1 — [RacePhysics] knows nothing about any
## of this. It is handed a [SurfaceProvider] and two [ObjectGrid]s and stepped;
## the presentation reads its state afterwards.
class_name RaceScene
extends Node3D

signal herring_changed(count: int)
signal race_completed(seconds: float, herring: int)

## Seconds between crossing the finish line and the menu coming up, so the
## finish deceleration is watchable instead of being cut off by a panel.
const FINISH_MENU_DELAY := 3.0

## The clip [CharacterRig] plays before the race starts. `char/<name>/start.lst`
## in the original: Tux is standing off to one side of the start point, waddles
## across to it, turns to face down the hill and drops onto his belly.
const INTRO_CLIP := &"start"
## What `CIntro::Enter` passes `CKeyframe::Init` as its height correction, and
## the reason the standing pose sits into the snow rather than on top of it.
const INTRO_HEIGHT_CORRECTION := -0.05
## `SetCameraDistance(4.0)` in `CIntro::Enter`. Same number as the racing
## default, named here because the intro is where the original says it.
const INTRO_CAMERA_DISTANCE := 4.0
## How far the body is dropped along its own up axis so the belly sits in the
## contact patch instead of on top of it.
##
## DEVIATION: the original draws the character at `cpos.y + TUX_Y_CORR` and
## nothing else. This used to be a local offset on the rig node, which is the
## same thing while the body's up axis is the surface normal — but during the
## intro it is not, and an offset along a standing penguin's local Y walked him
## sideways out of his own footprints.
const CHARACTER_SINK := 0.1

## Where "back" goes. Spelled out rather than reached for through [MainMenu]:
## that script already reaches in here for [member requested_course_path], and
## one direction of coupling between the two is enough.
const MAIN_MENU_SCENE := "res://scenes/main_menu.tscn"

@export_file("*.tscn") var course_scene_path: String = "res://courses/bunny_hill/course.tscn"
## What the shell asked for, and what it was last handed back.
##
## Static because a scene swap leaves nothing to set a property on: [MainMenu]
## writes it just before [method SceneTree.change_scene_to_file], `_ready` reads
## it, and [method load_course] keeps it current so the menu can highlight the
## course that was actually raced. Empty means [member course_scene_path] — the
## scene's own default, which is what opening `race.tscn` in the editor gets.
static var requested_course_path: String = ""
## Whether the shell was asked for a race without the start animation.
##
## Static for the same reason as [member requested_course_path]: a browser has no
## command line, so `?nointro=1` is read where the rest of the URL is read — in
## [MainMenu], one scene before this one exists.
static var play_intro: bool = true
@export var environment_preset: EnvironmentPreset
## Snow deformation costs a 1024² render target per frame; off on the lowest tier.
@export var snow_deformation: bool = true
## Placeholder character generated by the importer from `shape.lst` (§3.4).
## Swapping in authored skinned glTF art is a matter of pointing this at a
## different scene with the same joint names.
@export_file("*.tscn") var character_scene_path: String = "res://resources/characters/tux/tux.tscn"

var physics: RacePhysics
var course_root: CourseRoot
var terrain: TerrainRenderer
var snow_cpu: SnowField
var snow_gpu: SnowFieldGPU
var camera: ChaseCamera
var spray: SprayEmitter

var herring: int = 0
var race_time: float = 0.0
var running: bool = false
## True while the start animation is playing. The simulation is not stepped —
## the character is posed straight out of the migrated keyframe — but the course
## is drawn and any key skips to the race, exactly as `CIntro` does it.
var intro_running: bool = false
## True while the course menu is up. The simulation is not stepped and no
## player input is read, but the course stays loaded and on screen behind it.
var paused: bool = false

var menu: CourseMenu
## Directory name of the loaded course, so the menu can highlight it.
var current_course_dir: String = ""
## Incremented by [method restart]; lets a deferred callback tell whether the
## race it was started for is still the one running.
var _run_id: int = 0

var _input := RaceInput.new()
## Polls the held controls. A plain poll unless `--remote-keyboard` asked it to
## bridge a keyboard that arrives as zero-length pulses.
var _keys := KeyHoldFilter.new(PackedStringArray(["steer_left", "steer_right",
	"paddle", "brake", "jump", "trick_modifier"]))
var _player_node: Node3D
## The migrated character under [member _player_node], or null if none loaded.
var _rig: CharacterRig
var _sun: DirectionalLight3D

## Root motion of the clip currently playing, sampled against [member _intro_time].
var _intro_path: KeyframePath
var _intro_time: float = 0.0
## The camera framing the race wants back once the intro is over.
var _camera_mode_before_intro: ChaseCamera.Mode = ChaseCamera.Mode.BEHIND
var _camera_distance_before_intro: float = 4.0
## Whether this run wants the start animation at all. A scripted run does not:
## `--auto-input=` is a stand-in for a player, and four and a half seconds of Tux
## waddling in front of a frame counter would move every reference capture.
## `--no-intro` says the same thing explicitly.
var _intro_enabled: bool = true

## The terrain slide effect currently looping, or empty. ETR keeps the same
## pair of "last"/"new" ids in `racing.cpp`.
var _slide_cue: StringName = &""
## Reused by the once-a-frame terrain query behind the slide sound, so the
## audio does not allocate on the hot path.
var _slide_sample := SurfaceSample.new()

## Development-only scripted input, for headless verification shots.
## `--auto-input=carve` slaloms, `--auto-input=brake` drags the belly.
var _auto_input: String = ""

func _ready() -> void:
	camera = $ChaseCamera
	spray = $SprayEmitter
	snow_gpu = $SnowFieldGPU
	_player_node = $Player
	_install_character()
	_sun = $Sun
	if not requested_course_path.is_empty():
		course_scene_path = requested_course_path
	# A `--course=` on the command line outranks it: a capture run names the
	# course it wants, and the shell only ever passes on what it was given.
	for arg: String in OS.get_cmdline_user_args():
		if arg.begins_with("--auto-input="):
			_auto_input = arg.trim_prefix("--auto-input=")
		elif arg.begins_with("--camera="):
			if arg.ends_with("above"):
				camera.mode = ChaseCamera.Mode.ABOVE
			elif arg.ends_with("trail"):
				camera.mode = ChaseCamera.Mode.TRAIL
		elif arg == "--remote-keyboard":
			_keys.compensate = true
		elif arg == "--no-intro":
			play_intro = false
		elif arg.begins_with("--course="):
			course_scene_path = "res://courses/%s/course.tscn" % arg.trim_prefix("--course=")
	_intro_enabled = play_intro and _auto_input.is_empty()
	menu = $CourseMenu
	menu.course_chosen.connect(_on_course_chosen)
	menu.closed.connect(_on_menu_closed)
	menu.back_requested.connect(leave_to_main_menu)
	load_course(course_scene_path)

## Replace the stand-in capsule with the migrated character, if one exists.
func _install_character() -> void:
	if character_scene_path.is_empty() or not ResourceLoader.exists(character_scene_path):
		return
	for child: Node in _player_node.get_children():
		child.queue_free()
	var rig: Node3D = (load(character_scene_path) as PackedScene).instantiate()
	# The point mass sits at the centre of the body, and the rig arrives already
	# in Godot's frame — the importer bakes ETR's +Y-forward / +Z-belly model axes
	# out at the scene root (ETRImport.MODEL_TO_GODOT). So the rig sits at the
	# origin of the node that carries the body transform, and sitting it down
	# onto the contact patch is [constant CHARACTER_SINK], applied by whoever
	# writes that transform. Limbs following the carve is the procedural layer's
	# job (Phase 4); the canned keyframes are the other half of Phase 4 and go
	# through [CharacterRig].
	_player_node.add_child(rig)
	_rig = rig as CharacterRig

func load_course(path: String) -> void:
	_stop_slide_sound()
	Audio.halt_all()
	if course_root != null:
		course_root.queue_free()
		course_root = null
	if terrain != null:
		terrain.queue_free()
		terrain = null

	current_course_dir = path.get_base_dir().get_file()
	requested_course_path = path
	var packed: PackedScene = load(path)
	course_root = packed.instantiate()
	add_child(course_root)
	course_root.build_runtime()

	var course: CourseData = course_root.course_data

	snow_cpu = SnowField.new()
	course_root.surface.snow_field = snow_cpu

	physics = RacePhysics.new()
	physics.surface = course_root.surface
	physics.trees = course_root.trees
	physics.items = course_root.items
	physics.bounds_polygon = course.effective_play_bounds()
	physics.play_length = course.play_size.y
	physics.finish_brake = course.finish_brake
	physics.item_collected.connect(_on_item_collected)
	physics.substep_advanced.connect(_on_substep)
	physics.race_finished.connect(_on_race_finished)
	physics.tree_hit.connect(_on_tree_hit)

	terrain = TerrainRenderer.new()
	terrain.name = "Terrain"
	add_child(terrain)
	terrain.setup(course, course_root.surface)

	camera.surface = course_root.surface
	camera.reset()
	spray.surface = course_root.surface

	var preset: EnvironmentPreset = environment_preset
	if preset == null and course.environment_preset is EnvironmentPreset:
		preset = course.environment_preset
	if preset != null:
		_apply_environment(preset)

	restart()

## Put the race back at the start line. [param with_intro] is what separates the
## two ways in: choosing a course runs the start animation, where `r` mid-race is
## the original's Reset state and goes straight back to racing.
func restart(with_intro: bool = true) -> void:
	_run_id += 1
	var course: CourseData = course_root.course_data
	var start := Vector2(course.start_position.x, -course.start_position.y)
	physics.init_at(start.x, start.y)
	herring = 0
	race_time = 0.0
	running = true
	intro_running = false
	snow_cpu = SnowField.new()
	course_root.surface.snow_field = snow_cpu
	if snow_gpu != null:
		snow_gpu.reset()
	camera.reset()
	herring_changed.emit(herring)
	terrain.update_streaming(physics.pos)
	# Drop the authoring markers only once the batches and grids exist.
	course_root.release_markers()
	_stop_slide_sound()
	Audio.play_theme(course.music_theme, MusicTheme.Situation.RACE)
	# Marker for the browser harness: the course is loaded and the first frame
	# of simulation has run.
	print("RACE_READY %s %d chunks" % [course.display_name, terrain.chunk_count()])
	if with_intro and _intro_enabled:
		_begin_intro()

# ------------------------------------------------------------------
#                          the start animation
# ------------------------------------------------------------------

## `CIntro` in the original: the course is up and lit, the racing theme is
## already playing, and the character walks itself to the start line before the
## simulation is handed the controls.
##
## Nothing here touches [member physics]. The keyframe writes the body transform
## directly — the original does the same thing, overwriting `ctrl->cpos` from
## `CKeyframe::Update` every frame — and the simulation is stepped from the same
## start point it was initialised at once the animation is done, so there is
## nothing to hand over.
func _begin_intro() -> void:
	if _rig == null or not _rig.play_clip(INTRO_CLIP):
		return
	_intro_path = _rig.path_for(INTRO_CLIP)
	if _intro_path == null:
		_rig.stop_clip()
		return
	running = false
	intro_running = true
	_intro_time = 0.0
	# `set_view_mode(ctrl, ABOVE)` — the one camera that does not need a
	# direction of travel to point itself, which during the intro there is none of.
	_camera_mode_before_intro = camera.mode
	_camera_distance_before_intro = camera.distance
	camera.mode = ChaseCamera.Mode.ABOVE
	camera.distance = INTRO_CAMERA_DISTANCE
	_apply_intro_pose(0.0)
	camera.reset()
	camera.track(_player_node.global_position, Vector3.ZERO, Vector3.UP, 0.0)

func _step_intro(delta: float) -> void:
	_intro_time += delta
	if _intro_time >= _intro_path.duration():
		_end_intro()
		return
	_apply_intro_pose(_intro_time)
	_rig.seek_clip(_intro_time)
	camera.track(_player_node.global_position, Vector3.ZERO, Vector3.UP, delta)
	terrain.update_streaming(_player_node.global_position)

## Place the body where the keyframe says, on the hill rather than in it.
##
## `CKeyframe::Update` reads the authored Y as a clearance above the terrain and
## adds `Course.FindYCoord` to it, which is why a canned animation plays on any
## course. The rotation is the same yaw/pitch/roll the original hands node 0,
## turned into the frame this scene positions the character in — see
## [method CharacterRig.parent_basis_for].
func _apply_intro_pose(t: float) -> void:
	var course: CourseData = course_root.course_data
	var origin := Vector2(course.start_position.x, -course.start_position.y)
	var offset: Vector3 = _intro_path.offset_at(t)
	var x: float = origin.x + offset.x
	var z: float = origin.y + offset.z
	var basis: Basis = _rig.parent_basis_for(_intro_path.basis_at(t))
	var y: float = course_root.surface.height_at(x, z) + offset.y \
		+ PhysConst.TUX_Y_CORR + INTRO_HEIGHT_CORRECTION
	_player_node.global_basis = basis
	_player_node.global_position = Vector3(x, y, z) - basis.y * CHARACTER_SINK

## Hand over to the simulation. Reached either by the animation running out or by
## a key — the original aborts on any keypress too, and that is most of what the
## intro is for: it is a four-and-a-half second pause you are meant to be able to
## cut short.
func _end_intro() -> void:
	if not intro_running:
		return
	intro_running = false
	_intro_path = null
	if _rig != null:
		_rig.stop_clip()
	camera.mode = _camera_mode_before_intro
	camera.distance = _camera_distance_before_intro
	camera.reset()
	running = true

# ------------------------------------------------------------------
#                           course menu
# ------------------------------------------------------------------

func open_menu(result_text: String = "") -> void:
	if menu == null or menu.visible:
		return
	paused = true
	_stop_slide_sound()
	# The original's menus all play `param.menu_music`, and its game-over screen
	# plays the theme's win sting — which is the screen this becomes when it
	# comes up carrying a result. Opening the menu mid-race is the other case.
	if result_text.is_empty():
		Audio.play_menu_music()
	else:
		Audio.halt_all()
		Audio.play_theme(course_root.course_data.music_theme, MusicTheme.Situation.WON)
	menu.open(current_course_dir, running, result_text)

func _on_menu_closed() -> void:
	paused = false
	Audio.play_theme(course_root.course_data.music_theme, MusicTheme.Situation.RACE)

func _on_course_chosen(listing: CourseListing) -> void:
	paused = false
	if listing.dir == current_course_dir:
		restart()
		return
	course_scene_path = listing.scene_path
	load_course(course_scene_path)

## Drop the race and go back to the shell — the original's "abort race", which
## now has somewhere to go. The scene is replaced rather than kept around: a
## loaded course is most of the memory in the game and the menu behind it does
## not need a slope to draw over.
func leave_to_main_menu() -> void:
	_stop_slide_sound()
	Audio.halt_all()
	get_tree().change_scene_to_file(MAIN_MENU_SCENE)

## Esc opens the menu mid-race and closes it again — except during the start
## animation, where every key including that one skips to the race. That is
## `CIntro::Keyb`, which takes any press at all and aborts.
func _unhandled_input(event: InputEvent) -> void:
	if intro_running and not paused and _is_skip_press(event):
		get_viewport().set_input_as_handled()
		_end_intro()
		return
	if not event.is_action_pressed("menu"):
		return
	get_viewport().set_input_as_handled()
	if menu != null and menu.visible:
		menu.close()
	else:
		open_menu()

## A real press of anything a player could press. Echoes are held keys repeating
## and mouse motion is not a press, but a keyboard forwarded as zero-length
## pulses still arrives here as an ordinary [InputEventKey] — this is edge
## detection on the event itself, not on
## [method Input.is_action_just_pressed], and so does not need [KeyHoldFilter].
static func _is_skip_press(event: InputEvent) -> bool:
	if event is InputEventKey:
		return event.is_pressed() and not event.is_echo()
	return event is InputEventMouseButton and event.is_pressed() \
		or event is InputEventJoypadButton and event.is_pressed()

## What the menu shows above the list when it comes up after a finish.
func _result_line() -> String:
	return "%s   —   %s %.2f %s   %s %d" % [
		tr("RACE_OVER"), tr("TIME"), race_time, tr("SECONDS"), tr("HERRING"), herring]

func _apply_environment(preset: EnvironmentPreset) -> void:
	var we: WorldEnvironment = $WorldEnvironment
	var env: Environment = preset.to_environment()
	# The preset knows what `light.lst` said; the settings file knows how far
	# the player wants to see. Fog distance is the one place the two meet.
	Config.apply_fog(env, preset)
	we.environment = env
	_sun.light_color = preset.sun_color
	_sun.light_energy = preset.sun_energy
	_sun.look_at_from_position(Vector3.ZERO, -preset.sun_direction, Vector3.UP)
	_sun.directional_shadow_max_distance = _shadow_range_for(env)
	spray.particle_color = preset.particle_color
	if terrain != null:
		# What the ice reflects. The horizon end is the fog colour: at the
		# grazing angle a chase camera reflects at, ETR's sky is its own white
		# haze, and the skybox's nadir average is a downward direction ice
		# never shows you.
		terrain.set_sky_tint(preset.sky_zenith_color, preset.fog_color)

## How far directional shadows have to reach for this environment.
##
## Godot stops drawing them past `directional_shadow_max_distance` and fades
## them out over the last tenth. Set shorter than the visible slope, that cutoff
## is an arc centred on the camera: a shadowed bowl in front of the player and
## bare white hillside beyond it, moving with the view. The old fixed 120 m sat
## well inside a 190 m fog range and a 400 m far plane, so the arc was in shot
## most of the time.
##
## Tying the range to where fog has already washed the terrain out puts the
## cutoff somewhere it cannot be read. Four PSSM splits with blending keep the
## near-field resolution the longer range would otherwise cost.
##
## Read off the built [Environment] rather than off the preset, so a range the
## settings file has stretched carries the shadows out with it.
func _shadow_range_for(env: Environment) -> float:
	if not env.fog_enabled:
		return camera.far
	return clampf(env.fog_depth_end, 120.0, camera.far)

func _read_input(delta: float) -> void:
	if not _auto_input.is_empty():
		_scripted_input()
		return
	_keys.poll(delta)
	_input.left_turn = _keys.pressed("steer_left")
	_input.right_turn = _keys.pressed("steer_right")
	_input.stick_turn = _keys.axis("steer_left", "steer_right")
	_input.paddling = _keys.pressed("paddle")
	_input.braking = _keys.pressed("brake")
	_input.charging = _keys.pressed("jump")
	_input.trick_modifier = _keys.pressed("trick_modifier")

## Scripted stand-in for a player, so a headless run can produce the same
## carve every time.
func _scripted_input() -> void:
	_input.clear()
	match _auto_input:
		"carve":
			var phase: int = int(race_time / 1.6) % 2
			_input.left_turn = phase == 0
			_input.right_turn = phase == 1
			_input.paddling = true
		"brake":
			_input.braking = race_time > 3.0
		"paddle":
			_input.paddling = true

func _process(delta: float) -> void:
	if paused:
		return
	if Input.is_action_just_pressed("reset_race"):
		# The original's Reset state re-enters Racing, not Intro: `r` is for
		# getting back on the hill, not for watching the walk again.
		restart(false)
		return
	if intro_running:
		_step_intro(delta)
		return
	if not running:
		return

	_read_input(delta)
	physics.step(_input, delta)
	if not physics.finished:
		race_time += delta

	# Presentation follows the simulation; nothing here feeds back into it.
	var body := Basis(physics.orientation)
	_player_node.global_basis = body
	_player_node.global_position = physics.pos \
		+ Vector3(0.0, PhysConst.TUX_Y_CORR, 0.0) - body.y * CHARACTER_SINK

	_update_slide_sound()
	spray.flush(delta)
	camera.track(physics.pos, physics.vel, physics.plane_nml, delta)
	terrain.update_streaming(physics.pos)

	snow_cpu.recenter(physics.pos.x, physics.pos.z)
	snow_cpu.decay(delta)
	if snow_deformation and snow_gpu != null:
		snow_gpu.update(physics.pos.x, physics.pos.z, delta)
		terrain.set_trail_map(snow_gpu.trail_texture(), snow_gpu.window_origin(),
			snow_gpu.window_extent(), snow_gpu.max_depth)

## Stamp the deformation field from inside the substep loop, so a fast pass
## leaves a continuous trench instead of a dotted line at frame boundaries.
func _on_substep(h: float, pos: Vector3, speed: float) -> void:
	spray.emit_for_substep(physics, h, pos, speed)
	if physics.airborne:
		return
	var sample := SurfaceSample.new()
	course_root.surface.sample_into(pos.x, pos.z, sample)
	# `[trackmarks]`, not `[part]`: ETR keeps the two separate, and `strike_snow`
	# is the terrain where they disagree — it sprays but holds no track.
	if not sample.takes_trackmarks:
		return
	# How deep the belly is riding, capped by the terrain's own compression.
	var sink: float = clampf(sample.height - pos.y, 0.0, sample.compression_depth * 2.0)
	var amount: float = maxf(sink, 0.01) * minf(1.0, speed / 6.0)
	snow_cpu.stamp(pos.x, pos.z, PhysConst.TUX_WIDTH * 0.5, amount * h * 20.0)
	if snow_deformation and snow_gpu != null:
		snow_gpu.stamp(pos.x, pos.z, PhysConst.TUX_WIDTH * 0.5, amount)

func _on_item_collected(index: int) -> void:
	herring += 1
	course_root.hide_item(index)
	herring_changed.emit(herring)
	# Three cues, fired together, deliberately: the original has one voice per
	# sound, so a single pickup effect could never have layered with itself.
	Audio.play(&"pickup1")
	Audio.play(&"pickup2")
	Audio.play(&"pickup3")

func _on_tree_hit(_tree_pos: Vector3) -> void:
	Audio.play(&"tree_hit")

# ------------------------------------------------------------------
#                          terrain slide loop
# ------------------------------------------------------------------

## `PlayTerrainSound` in `racing.cpp`: the terrain under the player names a
## looping cue, which is halted when the terrain changes or the player leaves
## the ground. There is no speed or lean term — the original wrote one
## (`SlideVolume`) and left it commented out with "this function is not used
## yet", so the slide is on or off and nothing else.
##
## DEVIATION: the terrain is the dominant splat layer at the contact point,
## where the original took `Course.GetTerrainIdx(x, z, 0.5)` — the type holding
## at least half the blend, else nothing. Ours always resolves to a layer, so
## the sound changes a little earlier across a boundary; the flip side is that
## no blend of terrains is ever silent when both halves make a noise.
func _update_slide_sound() -> void:
	var cue: StringName = &""
	if not physics.airborne:
		course_root.surface.sample_into(physics.pos.x, physics.pos.z, _slide_sample)
		var layers: Array[TerrainLayer] = course_root.course_data.terrain_layers
		var id: int = _slide_sample.terrain_id
		if id >= 0 and id < layers.size() and layers[id] != null:
			cue = layers[id].slide_sound
	if cue != _slide_cue:
		if not _slide_cue.is_empty():
			Audio.halt(_slide_cue)
		_slide_cue = cue
	if not cue.is_empty():
		Audio.play(cue, true)

func _stop_slide_sound() -> void:
	if not _slide_cue.is_empty():
		Audio.halt(_slide_cue)
		_slide_cue = &""

func _on_race_finished() -> void:
	race_completed.emit(race_time, herring)
	_show_menu_after_finish(_run_id)

## Bring the menu up once the finish deceleration has played out, unless the
## player restarted or picked another course in the meantime.
func _show_menu_after_finish(run_id: int) -> void:
	await get_tree().create_timer(FINISH_MENU_DELAY).timeout
	if run_id == _run_id and not paused:
		open_menu(_result_line())
