## The race: wires the node-free simulation to everything that draws.
##
## Layering per godot-port-plan.md §4.1 — [RacePhysics] knows nothing about any
## of this. It is handed a [SurfaceProvider] and two [ObjectGrid]s and stepped;
## the presentation reads its state afterwards.
class_name RaceScene
extends Node3D

signal herring_changed(count: int)
signal race_completed(seconds: float, herring: int)

## Seconds between crossing the finish line and the menu coming up, so the
## finish deceleration is watchable instead of being cut off by a panel.
const FINISH_MENU_DELAY := 3.0

@export_file("*.tscn") var course_scene_path: String = "res://courses/bunny_hill/course.tscn"
@export var environment_preset: EnvironmentPreset
## Snow deformation costs a 1024² render target per frame; off on the lowest tier.
@export var snow_deformation: bool = true
## Placeholder character generated by the importer from `shape.lst` (§3.4).
## Swapping in authored skinned glTF art is a matter of pointing this at a
## different scene with the same joint names.
@export_file("*.tscn") var character_scene_path: String = "res://resources/characters/tux/tux.tscn"

var physics: RacePhysics
var course_root: CourseRoot
var terrain: TerrainRenderer
var snow_cpu: SnowField
var snow_gpu: SnowFieldGPU
var camera: ChaseCamera
var spray: SprayEmitter

var herring: int = 0
var race_time: float = 0.0
var running: bool = false
## True while the course menu is up. The simulation is not stepped and no
## player input is read, but the course stays loaded and on screen behind it.
var paused: bool = false

var menu: CourseMenu
## Directory name of the loaded course, so the menu can highlight it.
var current_course_dir: String = ""
## Incremented by [method restart]; lets a deferred callback tell whether the
## race it was started for is still the one running.
var _run_id: int = 0

var _input := RaceInput.new()
## Polls the held controls. A plain poll unless `--remote-keyboard` asked it to
## bridge a keyboard that arrives as zero-length pulses.
var _keys := KeyHoldFilter.new(PackedStringArray(["steer_left", "steer_right",
	"paddle", "brake", "jump", "trick_modifier"]))
var _player_node: Node3D
var _sun: DirectionalLight3D

## Development-only scripted input, for headless verification shots.
## `--auto-input=carve` slaloms, `--auto-input=brake` drags the belly.
var _auto_input: String = ""

func _ready() -> void:
	camera = $ChaseCamera
	spray = $SprayEmitter
	snow_gpu = $SnowFieldGPU
	_player_node = $Player
	_install_character()
	_sun = $Sun
	for arg: String in OS.get_cmdline_user_args():
		if arg.begins_with("--auto-input="):
			_auto_input = arg.trim_prefix("--auto-input=")
		elif arg.begins_with("--camera="):
			if arg.ends_with("above"):
				camera.mode = ChaseCamera.Mode.ABOVE
			elif arg.ends_with("trail"):
				camera.mode = ChaseCamera.Mode.TRAIL
		elif arg == "--remote-keyboard":
			_keys.compensate = true
		elif arg.begins_with("--course="):
			course_scene_path = "res://courses/%s/course.tscn" % arg.trim_prefix("--course=")
	menu = $CourseMenu
	menu.course_chosen.connect(_on_course_chosen)
	menu.closed.connect(_on_menu_closed)
	load_course(course_scene_path)
	# The course loads and renders first, then the menu opens over it: the
	# player picks against a live slope rather than a black screen, and the
	# browser harness still sees RACE_READY at the usual point. A scripted run
	# (`--auto-input=`) is driving the race itself and wants no menu at all.
	if _auto_input.is_empty():
		open_menu()

## Replace the stand-in capsule with the migrated character, if one exists.
func _install_character() -> void:
	if character_scene_path.is_empty() or not ResourceLoader.exists(character_scene_path):
		return
	for child: Node in _player_node.get_children():
		child.queue_free()
	var rig: Node3D = (load(character_scene_path) as PackedScene).instantiate()
	# The point mass sits at the centre of the body. The rig arrives already in
	# Godot's frame — the importer bakes ETR's +Y-forward / +Z-belly model axes
	# out at the scene root (ETRImport.MODEL_TO_GODOT) — so all that is left
	# here is to sit it down onto the contact patch along the surface normal.
	# Limbs following the carve is the procedural layer's job (Phase 4); this is
	# the rest pose from shape.lst.
	rig.position = Vector3(0.0, -0.1, 0.0)
	_player_node.add_child(rig)

func load_course(path: String) -> void:
	if course_root != null:
		course_root.queue_free()
		course_root = null
	if terrain != null:
		terrain.queue_free()
		terrain = null

	current_course_dir = path.get_base_dir().get_file()
	var packed: PackedScene = load(path)
	course_root = packed.instantiate()
	add_child(course_root)
	course_root.build_runtime()

	var course: CourseData = course_root.course_data

	snow_cpu = SnowField.new()
	course_root.surface.snow_field = snow_cpu

	physics = RacePhysics.new()
	physics.surface = course_root.surface
	physics.trees = course_root.trees
	physics.items = course_root.items
	physics.bounds_polygon = course.effective_play_bounds()
	physics.play_length = course.play_size.y
	physics.finish_brake = course.finish_brake
	physics.item_collected.connect(_on_item_collected)
	physics.substep_advanced.connect(_on_substep)
	physics.race_finished.connect(_on_race_finished)

	terrain = TerrainRenderer.new()
	terrain.name = "Terrain"
	add_child(terrain)
	terrain.setup(course, course_root.surface)

	camera.surface = course_root.surface
	camera.reset()
	spray.surface = course_root.surface

	var preset: EnvironmentPreset = environment_preset
	if preset == null and course.environment_preset is EnvironmentPreset:
		preset = course.environment_preset
	if preset != null:
		_apply_environment(preset)

	restart()

func restart() -> void:
	_run_id += 1
	var course: CourseData = course_root.course_data
	var start := Vector2(course.start_position.x, -course.start_position.y)
	physics.init_at(start.x, start.y)
	herring = 0
	race_time = 0.0
	running = true
	snow_cpu = SnowField.new()
	course_root.surface.snow_field = snow_cpu
	if snow_gpu != null:
		snow_gpu.reset()
	camera.reset()
	herring_changed.emit(herring)
	terrain.update_streaming(physics.pos)
	# Drop the authoring markers only once the batches and grids exist.
	course_root.release_markers()
	# Marker for the browser harness: the course is loaded and the first frame
	# of simulation has run.
	print("RACE_READY %s %d chunks" % [course.display_name, terrain.chunk_count()])

# ------------------------------------------------------------------
#                           course menu
# ------------------------------------------------------------------

func open_menu(result_text: String = "") -> void:
	if menu == null or menu.visible:
		return
	paused = true
	menu.open(current_course_dir, running, result_text)

func _on_menu_closed() -> void:
	paused = false

func _on_course_chosen(listing: CourseListing) -> void:
	paused = false
	if listing.dir == current_course_dir:
		restart()
		return
	course_scene_path = listing.scene_path
	load_course(course_scene_path)

## Esc opens the menu mid-race and closes it again. It replaces the original's
## "abort race": there is nowhere else to go back to yet.
func _unhandled_input(event: InputEvent) -> void:
	if not event.is_action_pressed("menu"):
		return
	get_viewport().set_input_as_handled()
	if menu != null and menu.visible:
		menu.close()
	else:
		open_menu()

## What the menu shows above the list when it comes up after a finish.
func _result_line() -> String:
	return "%s   —   %s %.2f %s   %s %d" % [
		tr("RACE_OVER"), tr("TIME"), race_time, tr("SECONDS"), tr("HERRING"), herring]

func _apply_environment(preset: EnvironmentPreset) -> void:
	var we: WorldEnvironment = $WorldEnvironment
	we.environment = preset.to_environment()
	_sun.light_color = preset.sun_color
	_sun.light_energy = preset.sun_energy
	_sun.look_at_from_position(Vector3.ZERO, -preset.sun_direction, Vector3.UP)
	_sun.directional_shadow_max_distance = _shadow_range_for(preset)
	spray.particle_color = preset.particle_color
	if terrain != null:
		# What the ice reflects. The horizon end is the fog colour: at the
		# grazing angle a chase camera reflects at, ETR's sky is its own white
		# haze, and the skybox's nadir average is a downward direction ice
		# never shows you.
		terrain.set_sky_tint(preset.sky_zenith_color, preset.fog_color)

## How far directional shadows have to reach for this environment.
##
## Godot stops drawing them past `directional_shadow_max_distance` and fades
## them out over the last tenth. Set shorter than the visible slope, that cutoff
## is an arc centred on the camera: a shadowed bowl in front of the player and
## bare white hillside beyond it, moving with the view. The old fixed 120 m sat
## well inside a 190 m fog range and a 400 m far plane, so the arc was in shot
## most of the time.
##
## Tying the range to where fog has already washed the terrain out puts the
## cutoff somewhere it cannot be read. Four PSSM splits with blending keep the
## near-field resolution the longer range would otherwise cost.
func _shadow_range_for(preset: EnvironmentPreset) -> float:
	if not preset.fog_enabled:
		return camera.far
	return clampf(preset.fog_end * preset.fog_distance_scale, 120.0, camera.far)

func _read_input(delta: float) -> void:
	if not _auto_input.is_empty():
		_scripted_input()
		return
	_keys.poll(delta)
	_input.left_turn = _keys.pressed("steer_left")
	_input.right_turn = _keys.pressed("steer_right")
	_input.stick_turn = _keys.axis("steer_left", "steer_right")
	_input.paddling = _keys.pressed("paddle")
	_input.braking = _keys.pressed("brake")
	_input.charging = _keys.pressed("jump")
	_input.trick_modifier = _keys.pressed("trick_modifier")

## Scripted stand-in for a player, so a headless run can produce the same
## carve every time.
func _scripted_input() -> void:
	_input.clear()
	match _auto_input:
		"carve":
			var phase: int = int(race_time / 1.6) % 2
			_input.left_turn = phase == 0
			_input.right_turn = phase == 1
			_input.paddling = true
		"brake":
			_input.braking = race_time > 3.0
		"paddle":
			_input.paddling = true

func _process(delta: float) -> void:
	if paused:
		return
	if Input.is_action_just_pressed("reset_race"):
		restart()
	if not running:
		return

	_read_input(delta)
	physics.step(_input, delta)
	if not physics.finished:
		race_time += delta

	# Presentation follows the simulation; nothing here feeds back into it.
	_player_node.global_position = physics.pos + Vector3(0.0, PhysConst.TUX_Y_CORR, 0.0)
	_player_node.global_basis = Basis(physics.orientation)

	spray.flush(delta)
	camera.track(physics.pos, physics.vel, physics.plane_nml, delta)
	terrain.update_streaming(physics.pos)

	snow_cpu.recenter(physics.pos.x, physics.pos.z)
	snow_cpu.decay(delta)
	if snow_deformation and snow_gpu != null:
		snow_gpu.update(physics.pos.x, physics.pos.z, delta)
		terrain.set_trail_map(snow_gpu.trail_texture(), snow_gpu.window_origin(),
			snow_gpu.window_extent(), snow_gpu.max_depth)

## Stamp the deformation field from inside the substep loop, so a fast pass
## leaves a continuous trench instead of a dotted line at frame boundaries.
func _on_substep(h: float, pos: Vector3, speed: float) -> void:
	spray.emit_for_substep(physics, h, pos, speed)
	if physics.airborne:
		return
	var sample := SurfaceSample.new()
	course_root.surface.sample_into(pos.x, pos.z, sample)
	if not sample.emits_particles:
		return
	# How deep the belly is riding, capped by the terrain's own compression.
	var sink: float = clampf(sample.height - pos.y, 0.0, sample.compression_depth * 2.0)
	var amount: float = maxf(sink, 0.01) * minf(1.0, speed / 6.0)
	snow_cpu.stamp(pos.x, pos.z, PhysConst.TUX_WIDTH * 0.5, amount * h * 20.0)
	if snow_deformation and snow_gpu != null:
		snow_gpu.stamp(pos.x, pos.z, PhysConst.TUX_WIDTH * 0.5, amount)

func _on_item_collected(index: int) -> void:
	herring += 1
	course_root.hide_item(index)
	herring_changed.emit(herring)

func _on_race_finished() -> void:
	race_completed.emit(race_time, herring)
	_show_menu_after_finish(_run_id)

## Bring the menu up once the finish deceleration has played out, unless the
## player restarted or picked another course in the meantime.
func _show_menu_after_finish(run_id: int) -> void:
	await get_tree().create_timer(FINISH_MENU_DELAY).timeout
	if run_id == _run_id and not paused:
		open_menu(_result_line())
