## The character, and everything a canned animation needs to drive it.
##
## Generated by the importer as the root of `resources/characters/<name>/<name>.tscn`
## and instanced by [RaceScene] under the node that carries the body's position
## and orientation. Authored art replaces the mesh; [b]this script and the joint
## names are the contract[/b] a replacement has to keep.
##
## The root's own basis is `ETRImport.MODEL_TO_GODOT` — the turn from ETR's model
## frame (+Y forward, +Z belly) into Godot's (+Y up, −Z forward), baked here so
## nothing downstream has to know about it. Everything below this node, including
## the migrated keyframes, is in the original's frame.
class_name CharacterRig
extends Node3D

## Root motion for each clip in [member animation_player]'s library, keyed by the
## same clip name. Empty for a clip that only moves joints. See [KeyframePath]
## for why this is not simply another track.
@export var keyframe_paths: Dictionary[StringName, KeyframePath] = {}

var skeleton: Skeleton3D
var animation_player: AnimationPlayer

func _ready() -> void:
	skeleton = get_node_or_null(^"Skeleton3D") as Skeleton3D
	animation_player = get_node_or_null(^"AnimationPlayer") as AnimationPlayer
	if animation_player != null:
		# The caller owns the clock. A canned animation runs while the
		# simulation is stopped, and it has to stay in step with the
		# [KeyframePath] the caller samples against the same time — which it
		# cannot do if the mixer is also advancing itself every frame.
		animation_player.callback_mode_process = \
			AnimationMixer.ANIMATION_CALLBACK_MODE_PROCESS_MANUAL

func has_clip(clip: StringName) -> bool:
	return animation_player != null and animation_player.has_animation(clip)

## Root motion for [param clip], or `null` if it has none.
func path_for(clip: StringName) -> KeyframePath:
	var path: KeyframePath = keyframe_paths.get(clip, null)
	return null if path == null or path.is_empty() else path

## Start [param clip] at t = 0 and hold it there. Returns whether the rig has it;
## a rig without the clip is not an error, it just does not animate.
func play_clip(clip: StringName) -> bool:
	if not has_clip(clip):
		return false
	animation_player.play(clip)
	animation_player.seek(0.0, true)
	return true

## Pose the skeleton at [param seconds] into the clip that is playing.
func seek_clip(seconds: float) -> void:
	if animation_player != null and animation_player.is_playing():
		animation_player.seek(seconds, true)

## Stop animating and put every joint back where `shape.lst` left it, which is
## the pose the race itself draws.
func stop_clip() -> void:
	if animation_player != null:
		animation_player.stop()
	if skeleton != null:
		skeleton.reset_bone_poses()

## The basis to give this node's parent so that the rig ends up rotated by
## [param model_rotation] in world space.
##
## A keyframe's yaw/pitch/roll is authored in the model frame — the original
## applies it to node 0, whose frame is the world, because there its model axes
## [i]are[/i] world axes. Here the rig root already spends its own basis turning
## that frame into Godot's, so the rotation has to be handed to the node above
## with that turn undone.
func parent_basis_for(model_rotation: Basis) -> Basis:
	return model_rotation * transform.basis.inverse()
