## Every playable character as a flat list, in the order `characters.lst` names
## them.
##
## GENERATED by the importer into [constant PATH], and generated for the same
## reason [CourseCatalog] is: `DirAccess` over `res://resources/characters/`
## finds nothing in a shipped build, because the exporter converts and remaps
## text resources out of their source paths. A resource written at import time
## is the only listing that is the same in the editor, in a native build and in
## the browser.
##
## The order is the file's, not alphabetical. ETR's registration screen is a
## [code]TUpDown[/code] over [code]Char.CharList[/code] starting at index 0, so
## the first record is the default, and the first record is Tux.
@tool
class_name CharacterCatalog
extends Resource

const PATH := "res://resources/characters.tres"

## The character every fallback lands on: `characters.lst` names Tux first and
## ETR's spinner opens on index 0.
const DEFAULT_DIR := "tux"

@export var entries: Array[CharacterListing] = []

## The generated catalog, or — if it is missing — one scanned from the character
## directories. The fallback only works when running from source, which is
## exactly where a stale checkout would be missing the file.
static func load_default() -> CharacterCatalog:
	if ResourceLoader.exists(PATH):
		var cat: CharacterCatalog = load(PATH)
		if cat != null and not cat.entries.is_empty():
			return cat
	return scan()

## Degraded index built from directory names alone, with the default first so
## that a scanned catalog still opens on Tux.
static func scan() -> CharacterCatalog:
	var cat := CharacterCatalog.new()
	var dir := DirAccess.open("res://resources/characters")
	if dir == null:
		return cat
	var names: PackedStringArray = dir.get_directories()
	names.sort()
	for name: String in names:
		var scene: String = "res://resources/characters/%s/%s.tscn" % [name, name]
		if not ResourceLoader.exists(scene):
			continue
		var listing := CharacterListing.new()
		listing.dir = name
		listing.display_name = name.capitalize()
		listing.scene_path = scene
		listing.preview_path = "res://resources/characters/%s/preview.png" % name
		if name == DEFAULT_DIR:
			cat.entries.insert(0, listing)
		else:
			cat.entries.push_back(listing)
	return cat

## The row for [param dir], or `null`. A hand-edited `penguinracer.cfg` and a
## `--character=` typo both arrive here.
func find(dir: String) -> CharacterListing:
	for e: CharacterListing in entries:
		if e.dir == dir:
			return e
	return null

## Position of [param dir] in the list, or 0 — the spinner has to open
## somewhere, and index 0 is where ETR's opens.
func index_of(dir: String) -> int:
	for i: int in entries.size():
		if entries[i].dir == dir:
			return i
	return 0

## Scene path for [param dir], falling back to whichever character is actually
## present: the named one, then [constant DEFAULT_DIR], then the first row.
##
## Every caller of this wants a rig, not a diagnosis — a `WebOneCourse`-style
## export that ships one character, or a config file naming one that has been
## deleted, should still race. Returns `""` only when there is no character at
## all, which [method RaceScene._install_character] reads as "keep the capsule".
func scene_path_for(dir: String) -> String:
	var listing: CharacterListing = find(dir)
	if listing == null:
		listing = find(DEFAULT_DIR)
	if listing == null and not entries.is_empty():
		listing = entries[0]
	if listing == null:
		return ""
	if not ResourceLoader.exists(listing.scene_path):
		return ""
	return listing.scene_path
